server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Akhilesh1571999/micro-configuration-service
          clone-on-start: true

